functionsDirectory = "/Users/Colin/Documents/Tinyblocks/Cursor/Jiyung's Portfolio 2/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/Colin/Documents/Tinyblocks/Cursor/Jiyung's Portfolio 2/_site"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/Colin/Documents/Tinyblocks/Cursor/Jiyung's Portfolio 2/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/admin"
to = "/admin/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]