backend:
  name: github
  repo: Tinyblocks/Jiyungportfolio
  branch: main
  base_url: https://jiyungleee.com
  auth_endpoint: /api/auth
media_folder: "images"
public_folder: "/images"
publish_mode: editorial_workflow
local_backend: true
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number", value_type: "int", min: 1900, max: 2100 }
      - { label: "Category", name: "category", widget: "select", options: ["personal", "client", "exhibition"], default: "personal" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - label: "Gallery Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Or gallery folder glob (e.g. /images/Seashells/*.{png,jpg})", name: "imagesFolder", widget: "string", required: false, hint: "Use this to auto-include all images from a folder." }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.njk" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/projects/{{slug}}/index.html" }
